#!/usr/bin/env python3
# fix-license-headers.py — normalise the wrong "LGPL 3.0" file headers.
#
# Two targets:
#   GROUP A (firmware / tooling source: *.cpp *.hpp *.h *.c, tests/webui/run-tests.js)
#       → GNU GPL 3.0 header (SPDX: GPL-3.0-only). Existing copyright line(s) preserved
#         verbatim (incl. Per-Olov Jernberg / possan where present).
#   GROUP B (the WebUI under sdcard_image/www/ — dadamachines-authored .html .js .css,
#            excluding the built *-bundle.js and vendored libs)
#       → proprietary header: "(c) <years> dadamachines / Johannes Elias Lohbihler.
#         All rights reserved." (German UrhG: the natural author must be named.)
#
# NOT touched (do these by hand — part of the LICENSE rewrite, see docs/MASTER-PLAN.md
# Phase 2): LICENSE, README.md, CONTRIBUTING.md, docs/about/10_credits.rst,
# docs/apps/groovebox.rst, docs/faq.rst, docs/index.rst — and the built bundles
# sdcard_image/www/js/{app-bundle.js,macro-bundle.js} (+ their .gz): regenerate those
# with sdcard_image/www/build-webui.sh AFTER the source .js files are fixed.
#
# Usage:
#   tools/fix-license-headers.py            # apply changes in place (review with `git diff`)
#   tools/fix-license-headers.py --dry-run  # show what would change, touch nothing
#   tools/fix-license-headers.py --list     # just print the audit (per-file classification)
#
# Run from the repo root. Idempotent: a file already carrying the new header is skipped.

import os, re, subprocess, sys, datetime

REPO_ROOT = subprocess.run(["git", "rev-parse", "--show-toplevel"],
                           capture_output=True, text=True, check=True).stdout.strip()
os.chdir(REPO_ROOT)

YEAR_NOW = datetime.date.today().year

# Files that must be edited by hand (LICENSE rewrite / docs prose) — never touched here.
MANUAL = {
    "LICENSE", "README.md", "CONTRIBUTING.md",
    "docs/about/10_credits.rst", "docs/apps/groovebox.rst",
    "docs/faq.rst", "docs/index.rst",
}
# Built/vendored web assets — regenerated by build-webui.sh, not edited here.
SKIP_WEB = re.compile(r"sdcard_image/www/js/(app-bundle|macro-bundle)\.js$")

CONTACT = "https://dadamachines.com/contact/"
LGPL_MARKERS = ("Lesser General Public", "lgpl-3.0", "LGPL 3.0", "Licensed under LGPL")

# ── header bodies (without comment delimiters; one logical line per list item) ──

def gpl_body(copyright_lines, descr):
    lines = list(descr) + [""]
    lines += copyright_lines
    lines += [
        "",
        "Licensed under the GNU General Public License (GPL 3.0):",
        "https://www.gnu.org/licenses/gpl-3.0.txt",
        "",
        f"A commercial licence is available — contact {CONTACT}",
        "",
        'Provided "as is" without any express or implied warranties.',
        "See LICENSE in the repository root for full terms.",
        "",
        "SPDX-License-Identifier: GPL-3.0-only",
    ]
    return lines

def proprietary_body(years, descr):
    return list(descr) + [
        "",
        f"(c) {years} dadamachines / Johannes Elias Lohbihler. All rights reserved.",
        "",
        "Not licensed under the GPL. This is the dadamachines TBD-16 WebUI; it",
        "communicates with the TBD-16 firmware over its REST API and is a separate",
        "program, not a derivative work of the firmware. Vendored components",
        "(Shoelace, webaudio-controls, Sortable, …) keep their own licences — see",
        "THIRD-PARTY.md.",
        "",
        f"Licensing enquiries: {CONTACT}",
    ]

# ── comment-delimiter handling ──

def comment_style(path):
    ext = os.path.splitext(path)[1].lower()
    if ext in (".html", ".htm"):
        return "html"
    if ext == ".css":
        return "block"
    if ext == ".js":
        return "line"          # these files use // headers
    # .cpp .hpp .h .c .cc .inl …
    return "block"

def wrap(body_lines, style):
    if style == "html":
        return "<!--\n" + "\n".join(("  " + l).rstrip() for l in body_lines) + "\n-->"
    if style == "line":
        FENCE = "// " + "═" * 63
        inner = "\n".join(("// " + l).rstrip() for l in body_lines)
        return f"{FENCE}\n{inner}\n{FENCE}"
    # block
    FENCE_OPEN, FENCE_CLOSE = "/***************", "***************/"
    return f"{FENCE_OPEN}\n" + "\n".join(body_lines).rstrip() + f"\n{FENCE_CLOSE}"

# ── locate & strip the leading header comment ──

def split_leading_comment(text):
    """Return (prefix, header_text, rest). prefix = optional shebang line.
       header_text = the leading comment block (or '' if none found)."""
    prefix = ""
    i = 0
    if text.startswith("#!"):
        nl = text.find("\n")
        prefix, text, i = text[:nl + 1], text[nl + 1:], nl + 1
    # skip blank lines
    m = re.match(r"\s*", text)
    lead_ws = m.group(0)
    body = text[len(lead_ws):]
    if body.startswith("<!--"):
        end = body.find("-->")
        if end == -1:
            return prefix, "", lead_ws + body
        end += 3
        return prefix, lead_ws + body[:end], body[end:]
    if body.startswith("/*"):
        end = body.find("*/")
        if end == -1:
            return prefix, "", lead_ws + body
        end += 2
        return prefix, lead_ws + body[:end], body[end:]
    if body.startswith("//"):
        # consume a contiguous run of // lines
        out_lines = []
        rest_lines = body.split("\n")
        idx = 0
        while idx < len(rest_lines) and rest_lines[idx].lstrip().startswith("//"):
            out_lines.append(rest_lines[idx]); idx += 1
        header = "\n".join(out_lines)
        rest = "\n".join(rest_lines[idx:])
        return prefix, lead_ws + header, ("\n" + rest if rest else rest)
    return prefix, "", lead_ws + body

CR_RE = re.compile(r"\(c\)\s*\d{4}.*", re.IGNORECASE)
YEARS_RE = re.compile(r"\(c\)\s*((?:\d{4})(?:\s*[-–]\s*\d{4})?)", re.IGNORECASE)

def extract_copyrights(header_text):
    out = []
    for raw in header_text.splitlines():
        line = raw.strip()
        # strip comment delimiters / fences
        line = re.sub(r"^(<!--|-->|/\*+|\*+/|//+|\*+|#+)", "", line).strip()
        line = re.sub(r"(\*+/|-->)\s*$", "", line).strip()
        if CR_RE.search(line):
            out.append(line)
    return out

_LIC_RE = re.compile(r"licen[sc]e|lgpl\b|\bgpl\b|gnu (lesser )?general public|spdx|gpl-3\.0|lgpl-3\.0|"
                     r"see license in the repository|provided \"as is\"|commercial use requires|"
                     r"dadamachines has a commercial|all express or implied|"
                     r"part of the dadamachines additions|copyright details for specific submodules|"
                     r"licensing enquiries|not licensed under", re.IGNORECASE)

def description_of(header_text):
    """The meaningful non-fence, non-copyright, non-licence lines from the old header
       (so the title + any 'Run:' / 'Vanilla JS' / etc. notes survive)."""
    out = []
    for raw in header_text.splitlines():
        line = raw.strip()
        line = re.sub(r"^(<!--|-->|/\*+|//+|\*+|#+)\s*", "", line).strip()
        line = re.sub(r"\s*(\*+/|-->)\s*$", "", line).strip()
        if not line:
            continue
        if set(line) <= set("═=*-_/ ~+#"):       # decorative fence
            continue
        if line.lower().startswith("(c)") or CR_RE.search(line):
            continue
        if line.lower().startswith("http") and ("gnu.org" in line or "spdx" in line.lower()):
            continue
        if _LIC_RE.search(line):
            continue
        out.append(line)
    return out or ["dadamachines TBD-16"]

# ── classification ──

def classify(path):
    if path in MANUAL:
        return "manual"
    if path.startswith("sdcard_image/www/"):
        if SKIP_WEB.search(path):
            return "bundle"
        ext = os.path.splitext(path)[1].lower()
        if ext in (".html", ".htm", ".js", ".css"):
            return "B"          # proprietary WebUI
        return "skip"
    ext = os.path.splitext(path)[1].lower()
    if ext in (".cpp", ".hpp", ".h", ".c", ".cc", ".inl") or path == "tests/webui/run-tests.js":
        return "A"              # GPLv3
    return "unknown"

def lgpl_files():
    out = subprocess.run(
        ["git", "grep", "-l", "-I", "-e", "LGPL", "-e", "Lesser General Public",
         "--", ".", ":!build/*", ":!managed_components/*", ":!*.gz", ":!docs/*.md", ":!tools/*"],
        capture_output=True, text=True).stdout.split()
    return sorted(out)

# ── main ──

def main():
    dry = "--dry-run" in sys.argv
    list_only = "--list" in sys.argv
    files = lgpl_files()
    buckets = {"A": [], "B": [], "manual": [], "bundle": [], "skip": [], "unknown": []}
    for f in files:
        buckets[classify(f)].append(f)

    if list_only or dry:
        print(f"# License-header audit ({len(files)} files contain LGPL)\n")
        for k, label in [("A", "→ GPLv3 (firmware/tooling) — handled by this script"),
                          ("B", "→ proprietary WebUI (© dadamachines / Johannes Elias Lohbihler) — handled by this script"),
                          ("bundle", "→ regenerate via sdcard_image/www/build-webui.sh AFTER the source .js are fixed — NOT edited"),
                          ("manual", "→ edit by hand (part of the LICENSE rewrite, MASTER-PLAN Phase 2) — NOT edited"),
                          ("skip", "→ ignored (non-source under www/)"),
                          ("unknown", "→ ⚠ unclassified — inspect manually")]:
            if buckets[k]:
                print(f"## {label}  ({len(buckets[k])})")
                for f in buckets[k]:
                    print(f"  {f}")
                print()
        if list_only:
            return

    changed = skipped = failed = 0
    for group in ("A", "B"):
        for path in buckets[group]:
            with open(path, "r", encoding="utf-8") as fh:
                text = fh.read()
            if not any(m in text[:4000] for m in LGPL_MARKERS):
                # already converted, or marker not in the header region
                skipped += 1
                continue
            prefix, header, rest = split_leading_comment(text)
            if not header or not any(m in header for m in LGPL_MARKERS):
                print(f"  ⚠ could not locate an LGPL header in {path} — skipped, fix by hand")
                failed += 1
                continue
            descr = description_of(header)
            crs = extract_copyrights(header)
            style = comment_style(path)
            if group == "A":
                if not crs:
                    crs = [f"(c) 2024-{YEAR_NOW} Johannes Elias Lohbihler for dadamachines."]
                body = gpl_body(crs, descr)
            else:  # B
                m = YEARS_RE.search(header)
                years = m.group(1).replace(" ", "") if m else f"2014-{YEAR_NOW}"
                body = proprietary_body(years, descr)
            new_header = wrap(body, style)
            # keep exactly one blank line between header and code
            rest = rest.lstrip("\n")
            new_text = prefix + new_header + "\n\n" + rest
            if new_text == text:
                skipped += 1
                continue
            if dry:
                print(f"  would update [{group}] {path}")
            else:
                with open(path, "w", encoding="utf-8") as fh:
                    fh.write(new_text)
                print(f"  updated   [{group}] {path}")
            changed += 1

    print(f"\n{'(dry-run) ' if dry else ''}done: {changed} file(s) "
          f"{'to be ' if dry else ''}updated, {skipped} already-ok/skipped, {failed} need manual attention.")
    if buckets["manual"]:
        print(f"reminder: {len(buckets['manual'])} files are edited by hand in MASTER-PLAN Phase 2 "
              f"(LICENSE/README/CONTRIBUTING + docs prose): " + ", ".join(buckets["manual"]))
    if buckets["bundle"]:
        print("reminder: after fixing the WebUI source, regenerate "
              + ", ".join(buckets["bundle"]) + " (+ .gz) via sdcard_image/www/build-webui.sh")
    if buckets["unknown"]:
        print("⚠ UNCLASSIFIED files (inspect manually): " + ", ".join(buckets["unknown"]))
        sys.exit(1)

if __name__ == "__main__":
    main()
