// =====================================================================================
// GrooveBoxRack routing regression test
//
// Captures the externally-observable result of every call to the four Pico-contract
// methods (setTrackMachine, setTrackBank, handleMidiNoteOn/Off) into a single text
// file.  When kept under version control as a "golden" output, this lets us refactor
// the internals (e.g. the switch-table → registry walk in commit-2 of the registry
// refactor) and prove byte-identical behaviour just by diffing the test's output.
//
// What it captures
//   1. setTrackMachine grid: for every (trackIndex 0..15, machineId in {"", and the
//      15 known ids}), call setTrackMachine(t, id, 1.0f) and dump the entire
//      GrooveBoxRack::GetRoutingSnapshot() (every chN.enabled + chN.volumeMultiplier
//      + every chN_xxx.enabled, in a fixed order).
//   2. setTrackBank grid: setTrackBank(t, idx) on every (t, idx in {0, 3, 7}); we
//      only get one sampler-bank index per track to inspect via GetRoutingSnapshot,
//      so we mostly just smoke-test that the call doesn't change other state.
//   3. handleMidiNoteOn/Off audio fingerprint: with every track set to its first
//      machine, run a grid of (channel 0..11, note ∈ {36,37,38,48,60}, vel ∈ {0,100}),
//      fire the note, run ~64 audio blocks, and dump the peak L/R amplitude.  Any
//      reroute (a note that used to fire ch1_db now firing ch1_ab, or no longer
//      firing anything) shows up as a different peak.
//
// Run:    ./routing-test              # prints "PASS" on diff-zero against golden
//         ./routing-test --regen      # rewrites tests/golden/groovebox-routing.txt
//                                     # (use ONLY when you've intentionally changed
//                                     # the contract and want to bless the new output)
//
// Build target: routing-test (see simulator/CMakeLists.txt)
// =====================================================================================

#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <cmath>
#include <string>
#include <vector>
#include <fstream>
#include <sstream>
#include "ctagSoundProcessor.hpp"
#include "ctagSoundProcessorFactory.hpp"
#include "ctagSPAllocator.hpp"
#include "ctagSoundProcessorGrooveBoxRack.hpp"
#include "helpers/ctagSampleRom.hpp"
extern "C" {
#include "esp_spi_flash.h"
}

using namespace CTAG::SP;

namespace CTAG { namespace RESOURCES { std::string sdcardRoot {"../../sdcard_image"}; } }

// All machine ids the rack knows about, plus the empty string for "no machine".
// Keep alphabetised so a new id appears at a predictable spot in the golden file.
static const char* kMachineIds[] = {
    "",         // empty == "track has no machine"
    "ab",       // Analog Bass Drum
    "as",       // Analog Snare Drum
    "cl",       // Clap
    "db",       // Digital Bass Drum
    "ds",       // Digital Snare Drum
    "fmb",      // FM Bass Drum
    "hh1",      // Hi-hat 1
    "hh2",      // Hi-hat 2
    "in",       // Audio Input
    "mo",       // Macro Oscillator
    "pp",       // PolyPad
    "ro",       // Rompler / sampler
    "rs",       // Rimshot
    "td3",      // TBD-03
    "wtosc",    // Wavetable Oscillator
};
static constexpr int kNumMachineIds = sizeof(kMachineIds) / sizeof(kMachineIds[0]);

// Drum-style channels share notes across tracks; melodic channels are pitched.
// Together this covers every channel handleMidiNoteOn / handleMidiNoteOff dispatches.
static const uint8_t kChannels[] = { 0, 1, 2, 3, 4, 5, 6, 9, 10, 11 };
static const uint8_t kNotes[]    = { 36, 37, 38, 48, 60 };
static const uint8_t kVels[]     = { 0, 100 };

// Re-create the rack from scratch.  Each phase wants a clean baseline; LoadPreset(0)
// is what the host calls on startup so we mirror that here.
static ctagSoundProcessor* freshRack() {
    auto* sp = ctagSoundProcessorFactory::Create("GrooveBoxRack",
                                                  ctagSPAllocator::AllocationType::STEREO);
    if (!sp) {
        std::fprintf(stderr, "Failed to construct GrooveBoxRack.\n");
        std::exit(2);
    }
    sp->LoadPreset(0);
    return sp;
}

static float blockPeak(const float* buf, int frames, bool right) {
    float p = 0.f;
    for (int i = 0; i < frames; i++) {
        float a = std::fabs(buf[i * 2 + (right ? 1 : 0)]);
        if (a > p) p = a;
    }
    return p;
}

int main(int argc, char** argv) {
    spi_flash_emu_init("../../tools/sample-tools/sample-rom.tbd");
    CTAG::SP::HELPERS::ctagSampleRom::RefreshDataStructure();

    bool regen = false;
    for (int i = 1; i < argc; i++) {
        if (std::strcmp(argv[i], "--regen") == 0) regen = true;
    }

    std::ostringstream out;
    out << "# GrooveBoxRack routing regression — auto-generated by routing-test\n";
    out << "# DO NOT EDIT by hand.  Regenerate with `./routing-test --regen` after a\n";
    out << "# deliberate behaviour change.\n";

    // ---------------------------------------------------------------------------------
    // Phase 1: setTrackMachine state grid
    // ---------------------------------------------------------------------------------
    {
        auto* sp = freshRack();
        auto* rack = static_cast<ctagSoundProcessorGrooveBoxRack*>(sp);
        out << "\n## phase 1: setTrackMachine state grid\n";
        for (int t = 0; t < 16; t++) {
            for (int m = 0; m < kNumMachineIds; m++) {
                rack->setTrackMachine(static_cast<uint8_t>(t), kMachineIds[m], 1.0f);
                out << "### setTrackMachine(t=" << t << ", id=\"" << kMachineIds[m] << "\", vol=1.0)\n";
                out << rack->GetRoutingSnapshot();
            }
        }
        delete sp;
    }

    // ---------------------------------------------------------------------------------
    // Phase 2: setTrackBank — should only touch the sampler's bank_index, not enabled
    // flags or mixer state.  Inspect just before/after to prove it.
    // ---------------------------------------------------------------------------------
    {
        auto* sp = freshRack();
        auto* rack = static_cast<ctagSoundProcessorGrooveBoxRack*>(sp);
        out << "\n## phase 2: setTrackBank no-side-effects\n";
        out << "### baseline\n" << rack->GetRoutingSnapshot();
        for (int t = 0; t < 16; t++) {
            for (uint16_t b : {0, 3, 7}) {
                rack->setTrackBank(static_cast<uint8_t>(t), b);
            }
        }
        out << "### after a full pass of setTrackBank(*, *) calls\n";
        out << rack->GetRoutingSnapshot();
        delete sp;
    }

    // ---------------------------------------------------------------------------------
    // Phase 3: handleMidiNoteOn/Off audio fingerprint.  For each (ch, note, vel):
    // - reset rack to the post-LoadPreset(0) state (where every track has its first
    //   machine assigned via setTrackMachineByDeviceValue),
    // - inject one note event,
    // - run 64 audio blocks,
    // - record peak L/R.
    //
    // We compare peaks against the golden, but a small tolerance is allowed for the
    // floating-point noise floor — peaks below 1e-5 are normalised to "0.00000" so
    // numerical drift from compiler differences doesn't trip false alarms.
    // ---------------------------------------------------------------------------------
    {
        out << "\n## phase 3: handleMidiNoteOn/Off audio fingerprint\n";
        float buf[32 * 2];
        float cv[4] = {0, 0, 0, 0};
        uint8_t trig[2] = {0, 0};
        ProcessData pd;
        pd.buf = buf; pd.cv = cv; pd.trig = trig;
        pd.sequencer_tempo = 12000; pd.sequencer_quantum = 4;
        pd.midi_bytes_length = 0; std::memset(pd.midi_bytes, 0, sizeof(pd.midi_bytes));

        auto fingerprint = [&](uint8_t ch, uint8_t note, uint8_t vel) {
            auto* sp = freshRack();
            // settle the rack — Process() a few empty blocks first
            for (int i = 0; i < 4; i++) { std::memset(buf, 0, sizeof(buf)); sp->Process(pd); }
            // fire the event directly (no MIDI parser — keeps this independent of [5])
            if (vel == 0) sp->handleMidiNoteOff(ch, note, 0);
            else sp->handleMidiNoteOn(ch, note, vel);
            float pL = 0.f, pR = 0.f;
            for (int i = 0; i < 64; i++) {
                std::memset(buf, 0, sizeof(buf)); sp->Process(pd);
                float l = blockPeak(buf, 32, false);
                float r = blockPeak(buf, 32, true);
                if (l > pL) pL = l;
                if (r > pR) pR = r;
            }
            delete sp;
            // floor low values so the test isn't sensitive to denormal noise.
            if (pL < 1e-5f) pL = 0.f;
            if (pR < 1e-5f) pR = 0.f;
            char line[128];
            // 3-decimal peaks are coarse enough to absorb tiny floating-point drift but
            // fine enough that a true reroute (different voice triggered) is obvious.
            std::snprintf(line, sizeof(line),
                          "ch=%2u note=%3u vel=%3u  peakL=%.3f peakR=%.3f\n",
                          ch, note, vel, pL, pR);
            return std::string(line);
        };

        for (uint8_t ch : kChannels) {
            for (uint8_t note : kNotes) {
                for (uint8_t vel : kVels) {
                    out << fingerprint(ch, note, vel);
                }
            }
        }
    }

    // ---------------------------------------------------------------------------------
    // Compare / regenerate against the golden file.
    // ---------------------------------------------------------------------------------
    const std::string actual = out.str();
    const std::string goldenPath = "../tests/golden/groovebox-routing.txt";

    if (regen) {
        std::ofstream fout(goldenPath);
        if (!fout) {
            std::fprintf(stderr, "Could not open %s for write.\n", goldenPath.c_str());
            spi_flash_emu_release();
            return 2;
        }
        fout << actual;
        std::printf("Golden file regenerated: %s (%zu bytes)\n",
                    goldenPath.c_str(), actual.size());
        spi_flash_emu_release();
        return 0;
    }

    std::ifstream fin(goldenPath);
    if (!fin) {
        std::fprintf(stderr,
            "No golden file at %s.\n"
            "Run with --regen to create one (only do this if you've intentionally\n"
            "changed the GrooveBoxRack routing contract).\n",
            goldenPath.c_str());
        spi_flash_emu_release();
        return 2;
    }
    std::stringstream ss; ss << fin.rdbuf();
    const std::string golden = ss.str();

    if (golden == actual) {
        std::printf("PASS: routing snapshot matches golden file (%zu bytes).\n", actual.size());
        spi_flash_emu_release();
        return 0;
    }

    // Print the first divergent line for a fast diagnostic.
    std::size_t i = 0;
    int lineNo = 1;
    while (i < golden.size() && i < actual.size() && golden[i] == actual[i]) {
        if (golden[i] == '\n') lineNo++;
        i++;
    }
    auto contextLine = [](const std::string& s, std::size_t pos) {
        std::size_t start = pos;
        while (start > 0 && s[start - 1] != '\n') start--;
        std::size_t end = pos;
        while (end < s.size() && s[end] != '\n') end++;
        return s.substr(start, end - start);
    };
    std::fprintf(stderr,
        "FAIL: routing snapshot differs from golden file at byte %zu (line %d).\n"
        "  golden : %s\n"
        "  actual : %s\n"
        "Write the actual output to /tmp/routing-actual.txt and `diff -u %s /tmp/routing-actual.txt`\n"
        "for the full diff.\n",
        i, lineNo,
        contextLine(golden, i).c_str(),
        contextLine(actual, i).c_str(),
        goldenPath.c_str());
    std::ofstream tmp("/tmp/routing-actual.txt");
    tmp << actual;

    spi_flash_emu_release();
    return 1;
}
